version: '0.2'
sources:
- database: local
  link: ''
  type: local
  branch: master
  cache_path: ''
  cache_timestamp: ''
  filters: null
- database: poo
  link: https://github.com/qxcodepoo/arcade.git
  type: clone
  branch: master
  cache_path: ''
  cache_timestamp: '2025-12-02 16:01:41'
  filters:
  - crud
expanded:
- poo@bloco_d-crud-com-mapas-e-enumerações
- poo@campanha-principal
- poo@bloco_d-crud-com-mapas-e-enumerações
tasks:
  poo@contato: '{rate:100, alone:10, study:60}'
flags:
  quests: 0
  tracks: 0
  tasks: 0
  graph: 0
  xray: 0
lang: py
selected: poo@contato
